### ISSUE TITLE
Help: Week Graphic not working

### ISSUE THREAD

**Issue by randkami** [YoshiCrafter29/YoshiEngine#90] opened 2022-03-15 20:03 UTC
So i have my week graphic set up and stuff, but it won't show up while editing nor in the story mode menu. I've tried redoing the week endlessly trying to fix it but it still just shows the haxe logo. Anyone know a fix? Using 1.6.1.

**Comment by YoshiCrafter29** [comment] 2022-03-16 21:17
It's a bug, and it was fixed in the dev channel.

The cause of the bug was that button sprites used "/" at the beginning, which broke assets paths. The bug is fixed.

**Closed by YoshiCrafter29** 2022-03-16 21:17 UTC
