### ISSUE TITLE
Enhancement: Not so very optimized

### ISSUE THREAD

**Issue by B01Coding** [YoshiCrafter29/YoshiEngine#17] opened 2022-01-25 13:33 UTC
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
v1.3.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
yes and no , deleting numbers gf ect
## Please describe your issue. Provide extensive detail and images if possible.
---the engine lags so hard tht isont know what to do and

**Comment by YoshiCrafter29** [comment] 2022-01-25 18:36
This is definitely weird, can you tell me in which menus/game the engine lags in ? Like the music and stuff ?

By far as i played the engine was under 3% CPU usage while in game.

Also, the lag is caused by lots of things being logged. Enable Developer Mode and check in logs in the pause menu, maybe something's up in there.

**Comment by YoshiCrafter29** [comment] 2022-01-26 17:11
Closing the issue cause we fixed it on Discord

But needa fix the optimization tho

**Closed by YoshiCrafter29** 2022-01-26 17:11 UTC
Labels: bug
